name: Build Native Binaries

on:
  workflow_call:
  workflow_dispatch:

permissions: {}
concurrency:
  group: uno-native-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  darwin:
    uses: ./.github/workflows/darwin.yml
    permissions:
      contents: read

  linux:
    uses: ./.github/workflows/linux.yml
    permissions:
      contents: read

  windows:
    uses: ./.github/workflows/windows.yml
    permissions:
      contents: read
